### ISSUE TITLE
Hugo Academic CLI v0.8.1 does nothing

### ISSUE THREAD

**Issue by wojciechmyszka** [GetRD/academic-file-converter#127]
Trying to use academic (in standalone environment). 
After instalation I got:
`Successfully installed academic-0.8.1 bibtexparser-1.1.0 ruamel.yaml-0.16.10 toml-0.10.2`
Script recognises -h option
`Hugo Academic CLI v0.8.1`
`https://github.com/wowchemy/hugo-academic-cli`
But run in import mode does nothing…
BibTeX file used attached

[k.md](https://github.com/GetRD/academic-file-converter/files/13549258/k.md)

**Comment by wojciechmyszka** [comment]
Forgot to mention:
Python 3.10.12
Ubuntu 22.04.3 LTS

**Comment by gcushen** [comment]
The version you are tyring to use, v0.8.1, is an ancient, unsupported version.

Try to use the latest version, **v0.11.2**.

**Comment by wojciechmyszka** [comment]
Thanks for answer.
Unfortunately pipx thinks that 0.8.1 is the latest version:
`pipx upgrade academic`
`academic is already at latest version 0.8.1 (location: /home/myszka/.local/pipx/venvs/academic)`

Trying to install from repository tells that I need newer version of Python:
`ERROR: Package 'academic' requires a different Python: 3.10.12 not in '>=3.11.5'`
So it is my problem now :-)

**Comment by IdoBar** [comment]
I had the same issue in a conda environment, because the conda recipe (in conda-forge) was only updated to v0.8.1
It will be useful to update the conda recipe to the recent version.

**Comment by gcushen** [comment]
> I had the same issue in a conda environment, because the conda recipe (in conda-forge) was only updated to v0.8.1 It will be useful to update the conda recipe to the recent version.

We do not release on Conda. We release via the official Python distribution on Pypi. We recommend to use the official Pypi  version. Any other version is unofficial.
